wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    code_path: code/run.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    start_time: 1629437419
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 2
      4: 3.7.7
      5: 0.12.0
      8:
      - 5
